before:
  hooks:
    - go mod tidy
builds:
  - ldflags:
      - -s -w -X github.com/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}/cmd.version={{.Version}}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{.Version}}-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=OS=linux"
      - "--build-arg=ARCH=amd64_v1"
  - image_templates:
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{.Version}}-arm64v8"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--build-arg=OS=linux"
      - "--build-arg=ARCH=arm64"
docker_manifests:
  - name_template: "{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{.Version}}"
    image_templates:
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{.Version}}-amd64"
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{.Version}}-arm64v8"
  - name_template: "{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:latest"
    image_templates:
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{.Version}}-amd64"
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{.Version}}-arm64v8"
