name: 03. Publish Artifacts

on:
  push:
    tags: ["*"]
  workflow_run:
    workflows:
      - 02. Bump & Tag
    types:
      - completed
    
permissions:
  contents: write

jobs:
  goreleaser:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Store Deploy Key in local file"
        # FYI: https://github.com/goreleaser/goreleaser-action/issues/326#issuecomment-1048899508
        run: |
          echo '${{ secrets.GH_HOMEBREW_DEPLOY_KEY }}' | base64 -d > '${{ github.workspace }}/gh_ssh_key'
          chmod 600 '${{ github.workspace }}/gh_ssh_key'
          head -n 1 '${{ github.workspace }}/gh_ssh_key'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_SSH_KEY: '${{ github.workspace }}/gh_ssh_key'
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
