name: tag

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - ".gitignore"
      - ".goreleaser.yml"
  workflow_dispatch:

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Tag version
        run:
          echo "main_tag=$(git describe --tags)" >> $GITHUB_ENV
      - name: Bump Version & Tagging
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
