name: tag

on:
  workflow_run:
    workflows: [test]
    types:
      - completed
  workflow_dispatch:

jobs:
  tagging:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Tag version
        run:
          echo "main_tag=$(git describe --tags)" >> $GITHUB_ENV
      - name: Bump Version & Tagging
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
